//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public System.DateTime EntryDt { get; set; }
        public string ContractNo { get; set; }
        public string AgreementType { get; set; }
        public string AgreementNo { get; set; }
        public string Title { get; set; }
        public string Scope { get; set; }
        public string Party { get; set; }
        public string CoordinatingPerson { get; set; }
        public string CoorCode { get; set; }
        public string Dept { get; set; }
        public Nullable<System.DateTime> EffectiveDt { get; set; }
        public Nullable<System.DateTime> ExpiryDt { get; set; }
        public string Remark { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Request { get; set; }
        public string TechTransfer { get; set; }
        public string Status { get; set; }
    }
}
