//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class International
    {
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string FileNo { get; set; }
        public string subFileNo { get; set; }
        public string Country { get; set; }
        public string Attorney { get; set; }
        public string ApplicationNo { get; set; }
        public Nullable<System.DateTime> FilingDt { get; set; }
        public string PublicationNo { get; set; }
        public Nullable<System.DateTime> PublicationDt { get; set; }
        public string Status { get; set; }
        public string SubStatus { get; set; }
        public string PatentNo { get; set; }
        public Nullable<System.DateTime> PatentDt { get; set; }
        public string Commercial { get; set; }
        public string Remark { get; set; }
        public string UserName { get; set; }
    }
}
