//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatentNewEntities : DbContext
    {
        public PatentNewEntities()
            : base("name=PatentNewEntities")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreement> Agreement { get; set; }
        public virtual DbSet<CompanyMaster> CompanyMaster { get; set; }
        public virtual DbSet<IPCountry> IPCountry { get; set; }
        public virtual DbSet<IPR_Category> IPR_Category { get; set; }
        public virtual DbSet<ListItemMaster> ListItemMaster { get; set; }
        public virtual DbSet<tbl_files_PatentRequest> tbl_files_PatentRequest { get; set; }
        public virtual DbSet<tbl_mst_filepath> tbl_mst_filepath { get; set; }
        public virtual DbSet<tbl_primary_receipt> tbl_primary_receipt { get; set; }
        public virtual DbSet<tbl_trx_AnnexureB1> tbl_trx_AnnexureB1 { get; set; }
        public virtual DbSet<tbl_trx_Applicants> tbl_trx_Applicants { get; set; }
        public virtual DbSet<tbl_trx_ApplicationAreas> tbl_trx_ApplicationAreas { get; set; }
        public virtual DbSet<tbl_trx_CoInventor> tbl_trx_CoInventor { get; set; }
        public virtual DbSet<tbl_trx_CommercialisationMode> tbl_trx_CommercialisationMode { get; set; }
        public virtual DbSet<tbl_trx_servicerequest> tbl_trx_servicerequest { get; set; }
        public virtual DbSet<tblAnnexureB1> tblAnnexureB1 { get; set; }
        public virtual DbSet<tblApplicants> tblApplicants { get; set; }
        public virtual DbSet<tblApplicationAreas> tblApplicationAreas { get; set; }
        public virtual DbSet<tblCommercialisationMode> tblCommercialisationMode { get; set; }
        public virtual DbSet<tbl_trx_dispute> tbl_trx_dispute { get; set; }
        public virtual DbSet<tbl_trx_DisputeActivity> tbl_trx_DisputeActivity { get; set; }
        public virtual DbSet<tbl_trx_DisputeAgreement> tbl_trx_DisputeAgreement { get; set; }
        public virtual DbSet<tblIndianPatent> tblIndianPatent { get; set; }
        public virtual DbSet<tbl_sec_International> tbl_sec_International { get; set; }
        public virtual DbSet<tblPCT> tblPCT { get; set; }
        public virtual DbSet<Attorney> Attorney { get; set; }
        public virtual DbSet<International> International { get; set; }
        public virtual DbSet<tbl_sec_receiptfileno> tbl_sec_receiptfileno { get; set; }
        public virtual DbSet<tbl_trx_disputeIDF> tbl_trx_disputeIDF { get; set; }
        public virtual DbSet<tbl_trx_duediligence> tbl_trx_duediligence { get; set; }
        public virtual DbSet<tblIDFRequest> tblIDFRequest { get; set; }
        public virtual DbSet<tblCoInventor> tblCoInventor { get; set; }
        public virtual DbSet<tbl_Copyright> tbl_Copyright { get; set; }
        public virtual DbSet<tbl_Trademark> tbl_Trademark { get; set; }
        public virtual DbSet<tbl_CR_Author> tbl_CR_Author { get; set; }
        public virtual DbSet<tbl_CR_Publish> tbl_CR_Publish { get; set; }
        public virtual DbSet<tbl_Trade_Applicantdetail> tbl_Trade_Applicantdetail { get; set; }
        public virtual DbSet<tbl_trx_Copyright> tbl_trx_Copyright { get; set; }
        public virtual DbSet<tbl_trx_CR_Author> tbl_trx_CR_Author { get; set; }
        public virtual DbSet<tbl_trx_CR_Publish> tbl_trx_CR_Publish { get; set; }
        public virtual DbSet<tbl_trx_Trade_Applicantdetail> tbl_trx_Trade_Applicantdetail { get; set; }
        public virtual DbSet<tbl_trx_Trademark> tbl_trx_Trademark { get; set; }
        public virtual DbSet<tbl_trx_IDFRequest> tbl_trx_IDFRequest { get; set; }
    }
}
