//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_servicerequest
    {
        public string SRNo { get; set; }
        public short Sno { get; set; }
        public long FileNo { get; set; }
        public string AttorneyID { get; set; }
        public string SharingParty { get; set; }
        public string Action { get; set; }
        public Nullable<short> Share { get; set; }
        public string MDocNo { get; set; }
        public Nullable<System.DateTime> IntimationDt { get; set; }
        public Nullable<System.DateTime> TargetDt { get; set; }
        public Nullable<System.DateTime> ActualDt { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public long trx_id { get; set; }
    }
}
