//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_primary_receipt
    {
        public decimal trans_id { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<System.DateTime> ReceiptDt { get; set; }
        public string Source { get; set; }
        public string Accno { get; set; }
        public string Party { get; set; }
        public string PartyRefNo { get; set; }
        public string ReceiptRef { get; set; }
        public string ReceiptDesc { get; set; }
        public Nullable<decimal> AmountINR { get; set; }
        public string IntimationRef { get; set; }
        public Nullable<System.DateTime> IntimationDt { get; set; }
        public string Comment { get; set; }
        public string IPAccno { get; set; }
        public Nullable<decimal> TransferAmt { get; set; }
        public Nullable<System.DateTime> TransferDt { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
