//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_dispute
    {
        public string DisputeNo { get; set; }
        public string DGroup { get; set; }
        public string Title { get; set; }
        public string DSource { get; set; }
        public string EstimatedValue { get; set; }
        public string PartyName { get; set; }
        public string RealizationValue { get; set; }
        public string Coordinator { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
