//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_DisputeActivity
    {
        public string DisputeNo { get; set; }
        public decimal SNo { get; set; }
        public string ActivityDate { get; set; }
        public string Forum { get; set; }
        public string ActivityType { get; set; }
        public string Remarks { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
