//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sec_International
    {
        public long trx_id { get; set; }
        public long FileNo { get; set; }
        public string Country { get; set; }
        public string PCT { get; set; }
        public string Appln_FilingNo { get; set; }
        public System.DateTime FilingDate { get; set; }
        public Nullable<bool> OfficeAction { get; set; }
        public Nullable<System.DateTime> OfficeActionDate { get; set; }
        public string Attorney { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public string PublicationNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int SNo { get; set; }
        public string PatentNo { get; set; }
        public Nullable<System.DateTime> PatentDate { get; set; }
    }
}
