//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trx_DisputeAgreement
    {
        public long agreement_trx_id { get; set; }
        public string Sno { get; set; }
        public string DisputeNo { get; set; }
        public string ContractNo { get; set; }
    }
}
