//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sec_receiptfileno
    {
        public decimal trans_id { get; set; }
        public string ReceiptNo { get; set; }
        public int SlNo { get; set; }
        public long FileNo { get; set; }
        public string Title { get; set; }
        public string RGroup { get; set; }
        public Nullable<decimal> SplitAmtInr { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
