//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIndianPatent
    {
        public long trx_id { get; set; }
        public long FileNo { get; set; }
        public string Attorney { get; set; }
        public string ApplicationNo { get; set; }
        public Nullable<System.DateTime> FilingDate { get; set; }
        public Nullable<System.DateTime> CompleteFilingDate { get; set; }
        public string PublicationPath { get; set; }
        public string PublicationNo { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public Nullable<bool> FERPlaced { get; set; }
        public Nullable<bool> FERIssued { get; set; }
        public Nullable<System.DateTime> FERIssueDate { get; set; }
        public string Status { get; set; }
        public string SubStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string PatentNo { get; set; }
        public Nullable<System.DateTime> PatentDate { get; set; }
    }
}
